### ISSUE TITLE
ldh never used

### ISSUE THREAD

**Issue by ISSOtm** [joeldipops/gbz80-pseudoOps#12]
Macros loading from memory (`addAny`, for example) do not use `ldh` when effective/possible.

**Comment by joeldipops** [comment]
* overhauled `ldAny` to select `ldh` over `ld` whenever possible. That is, `ldAny B, [Joypad]` expands to
`ldh A, [Joypad]`
`ld B, A`

* also wrote it to work with simple `ld`s so it can be used in place of any load op with no detriment ie `ldAny B, [HL]` ->  `ld B, [HL]`

* This allowed all other macros such as `orAny` to utilise `ldAny`
ie `orAny [Joypad], B` expands to 
`ldh A, [Joypad]`
`or A, B`
