### ISSUE TITLE
Incorrect side effects documentation

### ISSUE THREAD

**Issue by ISSOtm** [joeldipops/gbz80-pseudoOps#14]
If [this line](https://github.com/joeldipops/gbz80-pseudoOps/blob/02e1146fb0bc48580a642b848363a5db4fedb1f7/ops.inc#L192) is hit, flags are modified, whereas all doc comments state the macro doesn't affect them.

**Comment by joeldipops** [comment]
Fixed.  Doc comment now includes description of `ldAny [n16], 0` and `ldAny [r16], 0` cases.
