### ISSUE TITLE
`ldhAny` only loads *to* HRAM, not *from*

### ISSUE THREAD

**Issue by ISSOtm** [joeldipops/gbz80-pseudoOps#15]
Pretty much what is says on the "tin" :P

**Comment by joeldipops** [comment]
Have removed the ldh related macros.  ldAny will now select ldh over ld when appropriate, both to & from

**Comment by joeldipops** [comment]
Turns out the assembler always converts ld to ldh if it can (unless you use the -L flag) and my significant ldAny changes don't actually do what they're supposed to, afterall.

**Comment by ISSOtm** [comment]
"When it can" doesn't include labels, since those are managed by the linker
= post-assembly
