### ISSUE TITLE
`ld16` is bugged

### ISSUE THREAD

**Issue by ISSOtm** [joeldipops/gbz80-pseudoOps#17]
[This condition](https://github.com/joeldipops/gbz80-pseudoOps/blob/02e1146fb0bc48580a642b848363a5db4fedb1f7/ops.inc#L625) can never be met.

Unsure how to fix it.

**Comment by joeldipops** [comment]
rgbasm macro language can be very weird about brackets.  To get it working I had to surround the two terms with brackets.
`IF STRIN("\1", "[") == 1 && STRIN("\1", "]") == STRLEN("\1")`
vs
`IF (STRIN("\1", "[") == 1) && (STRIN("\1", "]") == STRLEN("\1"))`

All good now:
```
MEH EQU $c000
ld16 [MEH], BC
ld16 BC, [$ff10]
```
becomes
```
ld A, B
ld [$c000], A
ld A, C
ld [$c001], A
ldh A, $ff10
ld B, A
ldh A, $ff11
ld C, A
```

**Comment by ISSOtm** [comment]
I hardly see how that could work, since this expects `STRIN("\1", "[")` to return two different values.
