### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by ISSOtm** [joeldipops/gbz80-pseudoOps#5]
[This comment](https://github.com/joeldipops/gbz80-pseudoOps/blob/02e1146fb0bc48580a642b848363a5db4fedb1f7/addresses.inc#L69) states that this is for MBCs with higher ROM bank counts, when it's really per ROM, and only applies to MBC5.

**Comment by joeldipops** [comment]
Thanks, I hadn't tested the MBC stuff, I was just pulling it from  http://gbdev.gg8.se/wiki/articles/Memory_Bank_Controllers

Specifically this section under MBC5

> MBC5 (max 8MByte ROM and/or 128KByte RAM)
> ...
> 3000-3FFF - High bit of ROM Bank Number (Write Only)
> The 9th bit of the ROM bank number goes here.
>

**Comment by joeldipops** [comment]
Fixed
